# Generated by Django 3.1.2 on 2020-11-04 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.IntegerField(default=969157888929737137039563352095, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('movie', 'Any movie around the world.'), ('series', 'Any series except Asian ones.'), ('anime', 'Anime not cartoons.'), ('book', 'Book'), ('manga', 'Comics, graphics novels.'), ('asian drama', 'Series from Asia.')], max_length=12)),
                ('slug', models.SlugField(editable=False, max_length=7)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
                ('img_src', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('movie', 'Any movie around the world.'), ('series', 'Any series except Asian ones.'), ('anime', 'Anime not cartoons.'), ('book', 'Book'), ('manga', 'Comics, graphics novels.'), ('asian drama', 'Series from Asia.')], max_length=12)),
                ('web_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_img', models.ImageField(default='profile.png', upload_to='')),
                ('date_joined', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inclution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now=True)),
                ('added_to', models.CharField(max_length=7)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.collections')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.stuff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collections',
            name='stuffs',
            field=models.ManyToManyField(through='dashboard.Inclution', to='dashboard.Stuff'),
        ),
    ]
