# Generated by Django 3.1.2 on 2020-10-27 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('classification', models.CharField(choices=[('movie', 'Any movie around the world.'), ('series', 'Any series except Asian ones.'), ('anime', 'Anime not cartoons.'), ('book', 'Book'), ('manga', 'Comics, graphics novels.'), ('asian drama', 'Series from Asia.')], max_length=12)),
                ('web_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inclution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('added_to', models.CharField(max_length=5)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.collections')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.stuff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collections',
            name='stuffs',
            field=models.ManyToManyField(through='dashboard.Inclution', to='dashboard.Stuff'),
        ),
    ]
