# Generated by Django 3.1.2 on 2020-11-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='collection_id',
            field=models.IntegerField(default=650837393165878891567172865440, unique=True),
        ),
    ]
