# Generated by Django 3.1.2 on 2020-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='description',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='collections',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
