# Generated by Django 3.1.2 on 2020-10-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201031_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='slug',
            field=models.SlugField(default='7O2Mix', max_length=6),
        ),
        migrations.AlterField(
            model_name='inclution',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
