# Generated by Django 3.1.2 on 2020-11-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201104_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='collection_id',
            field=models.IntegerField(default=133588171799750776, unique=True),
        ),
    ]
