# Generated by Django 3.1.2 on 2020-10-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201031_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='slug',
            field=models.SlugField(default='7NnktN', editable=False, max_length=6, unique=True),
        ),
    ]
