# Generated by Django 3.1.2 on 2020-11-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201031_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='slug',
            field=models.SlugField(default='L49jYr', editable=False, max_length=6, unique=True),
        ),
    ]
