# Generated by Django 3.1.2 on 2020-11-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201107_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='synopsis',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='web_id',
        ),
    ]
