# Generated by Django 3.1.2 on 2020-11-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201101_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='collections',
            name='slug',
            field=models.SlugField(default='Zs5Ith', editable=False, max_length=6, unique=True),
        ),
    ]
