# Generated by Django 3.1.2 on 2020-11-09 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201107_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='stuff_uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
