# Generated by Django 3.1.2 on 2020-11-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201101_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='slug',
            field=models.SlugField(editable=False, max_length=6, unique=True),
        ),
    ]
